CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TYPE card_privacy AS ENUM ('PRIVATE', 'LINK_ONLY', 'PUBLIC');
CREATE TYPE expiration_type AS ENUM ('ETERNAL', 'UNTIL_TIME', 'PERIOD', 'END_OF_DAY');
CREATE TYPE notification_type AS ENUM ('ON_ENTER', 'ON_APPROACH', 'BOTH');
CREATE TYPE like_type AS ENUM ('LIKE', 'DISLIKE');
CREATE TYPE block_type AS ENUM ('USER_BLOCK', 'CARD_BLOCK');
CREATE TYPE notification_event_type AS ENUM (
    'GEO_ENTER',
    'GEO_APPROACH',
    'NEW_LIKE',
    'NEW_COMMENT',
    'NEW_MENTION',
    'CARD_PRIVATE',
    'MARKER_DELETED_IN_RADIUS',
    'REPORT_RECEIVED',
    'NEW_SUBSCRIBER'
);
