CREATE TABLE markers (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    card_id             UUID NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    created_by          UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    title               VARCHAR(200) NOT NULL,
    description         TEXT,
    location            GEOMETRY(Point, 4326) NOT NULL,
    latitude            DOUBLE PRECISION NOT NULL,
    longitude           DOUBLE PRECISION NOT NULL,
    images              TEXT[] NOT NULL DEFAULT '{}',
    tags                TEXT[] NOT NULL DEFAULT '{}',
    like_weight         INT NOT NULL DEFAULT 0,
    comment_count       INT NOT NULL DEFAULT 0,
    view_count          INT NOT NULL DEFAULT 0,
    allow_comments      BOOLEAN NOT NULL DEFAULT true,
    allow_likes         BOOLEAN NOT NULL DEFAULT true,
    is_draft            BOOLEAN NOT NULL DEFAULT false,
    notifications_enabled BOOLEAN NOT NULL DEFAULT true,
    notification_type   notification_type NOT NULL DEFAULT 'ON_ENTER',
    expires_at          TIMESTAMPTZ,
    expiration_type     expiration_type NOT NULL DEFAULT 'ETERNAL',
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
